name: cli
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/lex_cli/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'packages/lex_cli/**'
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check Lint and Prettier
    defaults:
      run:
        working-directory: packages/lex_cli
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Format
        run: npm run format

  build:
    runs-on: ubuntu-latest
    name: Build Code
    defaults:
      run:
        working-directory: packages/lex_cli
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Build
        run: npm run build
