name: demo

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/demo/**"
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - "packages/demo/**"
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check for Linting Errors
    defaults:
      run:
        working-directory: packages/demo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm install --only=dev
        shell: bash

      - name: Check for Linting Issues
        run: npm run prettier

  test:
    runs-on: ubuntu-latest
    name: Run UI Tests
    defaults:
      run:
        working-directory: packages/demo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM Install
        run: npm install --only=dev
        shell: bash

      - name: Run UI Tests
        run: npm run test

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build (and Deploy)
    defaults:
      run:
        working-directory: packages/demo
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: packages/demo/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: hicsail/saas-demo:latest
          build-args: |
            VITE_GRAPHQL=${{ secrets.VITE_GRAPHQL }}
            VITE_DEFAULT_LEX=${{ secrets.VITE_DEFAULT_LEX }}

      - name: Push to Deployment
        uses: fjogeleit/http-request-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}
          preventFailureOnNoResponse: true
