name: lex
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/lex_service/**'
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - 'packages/lex_service/**'
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    name: Check Lint and Prettier
    defaults:
      run:
        working-directory: packages/lex_service
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Format
        run: npm run format

  build:
    runs-on: ubuntu-latest
    name: Build Code
    defaults:
      run:
        working-directory: packages/lex_service
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Build
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Container
    defaults:
      run:
        working-directory: packages/lex_service
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker Build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=lex
          cache-to: type=gha,mode=max,scope=lex
